### ISSUE TITLE
Hello from valtio-yjs

### ISSUE THREAD

**Issue by dai-shi** [joebobmiles/zustand-middleware-yjs#1]
Hi, just wanted to say hello.
I'm trying a project valtio-yjs, but it's still **very far** from MVP. There might be something I could learn from your project.

I'm also interested in @YousefED 's work. (My hope was/is I could just use it without me creating a new one.)
https://github.com/YousefED/reactive-crdt/issues/5

**Comment by joebobmiles** [comment]
Let me know if you've got any questions! I am ashamed to say I have a few things to learn from this code as well, as all I really know about how it works is the bare essentials I learned from [YJSON](/joebobmiles/yjson) and the fact that the tests pass. 😅 

I'm going to close this issue, but we can continue the conversation via [email](mailto:joe@jrm.dev) or [twitter](https://twitter.com/@joebobmiles).
